travis:
  secure:
    BINSTAR_TOKEN: oKCDKKmLvS/nTWxAjdisV6DHWkC9o8AtUniQBBVNuuPR/EAND4HtvJWICXJC7rouKC/6NI1sSyGwVy/toD/NxRSVYqLWMmE9HNJmbkNqcLcQiV9GJnLjhPTa//3R6jw3xHbh+cv1lqIRDBR86Ban3YiK2VhhOSd5PJ9X+KcPcyjdWpow6C/q3f7HK1KvSkQZ2LV7rzIL66CUiTtVET3XMBgmQVokbNI/ysXFe23ru1cx+XeeES2QJy6RkckiHhzHrsYW/pV+Ug1wfaRBEor3cDqitbDM7VQRVQ2Incf4dwuXOwrc5yb7NQz901LF8S/8kYS8bIYoQ7RCMKUXeVTCkkPYGfeLRDLgSZERNfD4bhpiXyAeylK+vTg4wd3y6nk85fNbyb0MGNFUb+ZLPJsvxc0j7gwTXg4uwzYP8Fv93W6R42RT3HDMCCNzqXFJODVoKHPI+XIRIboBDgDtPoqnxtWApyyAK/JLSA+VGV3beECqkC998nApDasr9bH4dOdt08NA4D2Q5j/b2xY+H0mrhw8wblC5UQw2Yam9PE+buLqHhxUqPdkqAiyApBe/VuDg7uj8vScjuPxUpJijLy+RMaDjX6cDFtIs+dGAW1HUTuHsX7rfgmexg0mtSF5lInuIeJJF4xNJLdUlbhGEpx5b+psEbfCo4mSr4+yjCx0NeKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
