travis:
  secure:
    BINSTAR_TOKEN: V4JgMpxeBXi79BIv8P2WQnmqDMWz3DrKV7v55UUdpcJhblT4ogcP5MVox3Rgvho37jsSdusEPa4wSJzD3kOg3t8yM5vM+YNVc2EGFOBdiSk796agGgQM6NVnjn8eA8JOcfYPsoXCXBMklj+IPyGprZr7qycDVvHNHVhqLj8ftYe1U7xhgAu1xxht8VZMSpNVabiad2W7GIULvQhUl8/ngJ8BdB0FMUiZscj8cW7BTkVk0q8SdMi3HlN7LxdFShu8kftY2rb0V5C6ASBQ9U4sr6dj2Td/upPOhN3vDWPsT0XKDu8ZuDcUb6vu92ndRuXSasp9wvA8dSljDGCjy8klkFooAxxrdoSfncFqFvE6Eox3j2mkpT8eY6bTENVGJnYAqXml3DGkf7OoIUU9yFV8bWcPUpKCczyb4hAu4ve8/P6wSiH5TDs3HPQX3/aGfTox4XTNM4/p0OSDfegcnYjIyCgcPf4V1R9Y49Ld/Ooo7OYtoChfS6mfCwdsKYtX3RaanZ/P0ii959TXVaTT7I+jyMLlwaNITUhyovCIwx9iDFHJbr3ZSBqDYu9J/ri6ZKsfR2bFkIHKvivb1CIfb7TN1QFhcRWlo2A3EnK+qI5gYnshTMNdI0fEZ6y99h+WQ/Csyx+kgHrtPg0utCegQxBYqR9dJPxTxiEWZdGYNMsbqjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
